Add NIBSS module
enyata/innovation-sandbox-php pull request #1
Opened 2020-02-18 11:34 UTC by mezlet

2020-02-18 14:06 UTC, akinjide requested changes
Include test and code linters

2020-02-18 14:06 UTC, akinjide commented on composer.json
> +    "description": "PHP package for Innovation Sandbox",
Is this package not versioned?

2020-02-18 14:06 UTC, akinjide commented on composer.json
> +    ],
We don't need authors

2020-02-18 14:06 UTC, akinjide commented on composer.json
> +        "fzaninotto/faker": "^1.9@dev"
This should be in `require-dev`

2020-02-18 14:06 UTC, akinjide commented on src/Common/HttpRequest.php
> +        $this->baseURL = ($credentials["host"] ? $credentials["host"] : 'https://innovation-sandbox-backend.herokuapp.com');
change default URL to production

2020-02-18 14:06 UTC, akinjide commented on src/Common/HttpRequest.php
> +            "body" => $encrypetedBVN
should be `encryptedBVN` not `encrypetedBVN`

2020-02-20 08:13 UTC, mezlet commented on src/Common/HttpRequest.php
> +            "body" => $encrypetedBVN
resolved

2020-02-20 08:13 UTC, mezlet commented on src/Common/HttpRequest.php
> +        $this->baseURL = ($credentials["host"] ? $credentials["host"] : 'https://innovation-sandbox-backend.herokuapp.com');
resolved

2020-02-20 08:27 UTC, mezlet commented on composer.json
> +    ],
resolved

2020-02-20 08:29 UTC, mezlet commented on composer.json
> +        "fzaninotto/faker": "^1.9@dev"
resolved

2020-02-20 08:36 UTC, mezlet commented on composer.json
> +    "description": "PHP package for Innovation Sandbox",
I omitted it because of this
![Screenshot 2020-02-20 at 9 34 35 AM](https://user-images.githubusercontent.com/20390946/74915373-6582fc80-53c4-11ea-836f-4c924d3feef8.png)

2020-02-20 08:36 UTC, mezlet commented on composer.json
> +    "description": "PHP package for Innovation Sandbox",
what do you think?

2020-02-21 09:52 UTC, akinjide commented on composer.json
> +    "description": "PHP package for Innovation Sandbox",
What's the convention for PHP modules?

2020-02-21 09:53 UTC, akinjide commented on composer.json
> +    ],
Remove the authors array, we don't need it

2020-02-21 09:53 UTC, akinjide commented on composer.json
> +        "fzaninotto/faker": "^1.9@dev"
move both to `require-dev`

2020-02-21 09:53 UTC, akinjide requested changes
Include .travis.yml file use node version as sample.

2020-02-21 09:55 UTC, akinjide commented on composer.json
> +    "name": "innovation-sandbox/nibss",
Make the composer.json name generic `innovation-sandbox` since you will be including sterling module

2020-02-21 13:02 UTC, mezlet commented on composer.json
> +    "description": "PHP package for Innovation Sandbox",
most of the packages I have seen don't have named versions.

2020-02-21 13:04 UTC, mezlet commented on composer.json
> +        "fzaninotto/faker": "^1.9@dev"
but the guzzlehttp package is a core module for this package.

2020-02-21 13:32 UTC, mezlet commented on composer.json
> +    ],
done

2020-02-21 13:33 UTC, mezlet commented on composer.json
> +    "name": "innovation-sandbox/nibss",
done

2020-02-24 15:27 UTC, akinjide commented on composer.json
> +    "description": "PHP package for Innovation Sandbox",
okay, we will proceed without version

2020-02-24 15:27 UTC, akinjide commented on travis.yml
> +  - '7.2'
Include PHP 7.4 here

2020-02-24 15:58 UTC, merged